name: Python application with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Python environment
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4: Lint with flake8
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Step 5: Debug test discovery
    - name: Debug test discovery
      run: pytest --collect-only

    # Step 6: Run tests
    - name: Run tests
      run: |
        export PYTHONPATH=$GITHUB_WORKSPACE
        pytest

    # Step 7: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t simple-web-app .

    # Step 8: Run the Docker container
    - name: Run Docker container
      run: |
        docker run -d -p 5000:5000 --name monthly-calculator-container simple-web-app

    # Optional: Push Docker image to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker image to GitHub Container Registry
      run: |
        docker tag monthly-calculator-app ghcr.io/${{ github.repository_owner }}/monthly-calculator-app:latest
        docker push ghcr.io/${{ github.repository_owner }}/monthly-calculator-app:latest